;; GENERATED by hive-dsl.portable-golden-regen — do not edit by hand.
;; Regenerate: clojure -M:dev -e "(require 'hive-dsl.portable-golden-regen)(hive-dsl.portable-golden-regen/-main)"
(ns hive-dsl.portable-golden
  "Values observed on the JVM reference arm, one per case id in
   hive-dsl.portable-cases. Host-free data only.")

(def expected
{:coerce/int-pad
 {:error :coerce/invalid-int,
  :message "Expected integer, got \" 42 \"",
  :value " 42 "},
 :coerce/double-pad {:ok 1.5},
 :agentop/recover {:ok :fixed},
 :result/map-ok {:ok 3},
 :result/err? true,
 :result/rescue-nil nil,
 :result/bind {:ok 3},
 :agentop/fan-in-err :partial,
 :coerce/double-bad
 {:error :coerce/invalid-double,
  :message "Expected number, got \"x\"",
  :value "x"},
 :adt/schema-pred nil,
 :coerce/enum-bad :coerce/invalid-enum,
 :coerce/enum-ok {:ok :both},
 :coerce/int-num {:ok 7},
 :agentop/retry-ok {:ok :first},
 :batch/normalize-map [{:a 1}],
 :coerce/double {:ok 1.5},
 :result/err {:error :boom, :a 1},
 :agentop/budget-out
 {:error :budget-exhausted, :budget/remaining 1, :budget/needed 3},
 :adt/valid false,
 :coerce/int {:ok 42},
 :swarm/status? true,
 :result/rescue-ok 42,
 :result/try-effect :effect/exception,
 :conv/->status nil,
 :batch/normalize-vec [[:db/add 1 :a 2]],
 :result/let-ok-short {:error :stop},
 :result/ok? true,
 :taxonomy/known-error false,
 :result/rescue-coll [],
 :conv/status? true,
 :coerce/int-bad
 {:error :coerce/invalid-int,
  :message "Expected integer, got \"x\"",
  :value "x"},
 :swarm/->status
 {:adt/variant :slave-status/working, :adt/type :SlaveStatus},
 :result/ok {:ok 1},
 :result/rescue-log :fb,
 :coerce/boolean {:ok true},
 :resource/scope-acq {:ok :db},
 :swarm/->status-bad nil,
 :result/rescue-fn :fb,
 :coerce/keyword {:ok :abc},
 :result/rescue-meta "boom",
 :result/let-ok {:ok 6},
 :agentop/budget-ok {:ok :ran},
 :coerce/vec-csv
 {:error :coerce/invalid-vec,
  :message "Expected array, got string: \"a,b,c\"",
  :value "a,b,c"},
 :swarm/status
 {:adt/variant :slave-status/zombie, :adt/type :SlaveStatus},
 :result/map-ok-err {:error :e},
 :adt/type :Foo,
 :agentop/fan-in-ok {:ok [1 2]},
 :agentop/tap {:ok 1},
 :batch/count 0}
)
