(ns hive-dsl.portable-golden-regen
  "JVM-side generator for the oracle's frozen values.

   The JVM is the reference arm: it runs `hive-dsl.portable-cases/cases` and
   writes `hive-dsl.portable-golden`, which the host-free replay runner then
   diffs against on every runtime.

   The frozen values ship as a generated `.cljc` def rather than an EDN file
   read at run time: reading a file needs host IO, and the whole point of the
   replay runner is that it needs none.

   Regenerate after adding a case:
     clojure -M:dev -e \"(require 'hive-dsl.portable-golden-regen)(hive-dsl.portable-golden-regen/-main)\""
  (:require [clojure.java.io :as io]
            [clojure.pprint :as pp]
            [hive-dsl.portable-cases :as cases]))

(def target "test/hive_dsl/portable_golden.cljc")

(defn render
  "Source text of the golden namespace for `observed`.

   The frozen map is emitted under `quote`: a case may legitimately observe a
   symbol or a list (hive-dsl.typed.emit returns Typed Clojure syntax AS DATA),
   and an unquoted one is code — every runtime tried to resolve
   `typed.clojure/HMap` while loading the golden namespace."
  [observed]
  (str ";; GENERATED by hive-dsl.portable-golden-regen — do not edit by hand.\n"
       ";; Regenerate: clojure -M:dev -e \"(require 'hive-dsl.portable-golden-regen)"
       "(hive-dsl.portable-golden-regen/-main)\"\n"
       "(ns hive-dsl.portable-golden\n"
       "  \"Values observed on the JVM reference arm, one per case id in\n"
       "   hive-dsl.portable-cases. Host-free data only.\")\n\n"
       "(def expected\n"
       "  (quote\n"
       ;; Namespaced-map syntax (#:adt{...}) is not read by every target
       ;; runtime, so the frozen data is printed with fully-qualified keys.
       (binding [*print-namespace-maps* false]
         (with-out-str (pp/pprint observed)))
       "))\n"))

(defn -main [& _]
  (let [observed (cases/observe)]
    (io/make-parents target)
    (spit target (render observed))
    (println (str "wrote " target " (" (count observed) " cases)"))))
